language: node_js
node_js:
- '8'
before_script:
- yarn clean cache
- yarn install
- npm rebuild node-sass
- yarn build
- ls
notifications:
  email:
    recipients:
    - sloot@slootdev.com
    on_success: always
    on_failure: always
deploy:
  provider: s3
  access_key_id: AKIAJFMT4CDZFWNQFVXA
  secret_access_key:
    secure: O+PdH8sX69RarZlsbJFh/ad7a6d97EBVQ3BEZjMravLLxqROJOWsF5ei2ll0LtR9xMfCo9b/gk/3rOEClwomlsMFx/cM6ZWBZUHgFAm5tR3pgakfc5Q0BFguZSpSNXwFxxCQdEimQA3ddUl40nUWEDsUeGl47O9NHfDNmoy3E/Eip2Q2jSSXYgy0mJoqiYNHEFKQ4Hul1dGo48gw2kC/TQ1MhnSW42jjQMT2/X08CYzRlvZ5NRghGcgN0tT9EHwSJO4RjZ8qqBnKrzq1bLSGRMxytEast92MtKrNym8I+/ho+/uqSyfVYjOqyugvbtAxJicYt0JAVctYBiOtRCN5W10Q6DuH7L0bPmxeTh+0bcyLItSIk3poSS66sAyIWiwFW5jeEVXEE6xVczKTSf1V6ejCQZFcLDe8hvcPe9godyjP34VC7InMsG1QL6jEOLMDNFMKYiu4sVNCGw7Q4LFp6xzAnHM/vqB5+55A6orDcgGq2PE2UZL7Fyn4W/XJz7MjsTPOoEC8yt0hqRhu2JZx8dYSkVC/cCRrlMrwlaCNJNPoIfAcWQS0tKLURFGE+HXCgUStpFfAlRuMyLxRNbBzKSf3bjafCN0fJ+3iKLX/F9myT3qcQlejCH3yu2n3JcjQVF+efpgEoiLLc2x8h65AKhsTYkR5EPOttsH3/68e8qI=
  bucket: reactstorefrontcoffee
  local-dir: build
  skip_cleanup: true
  on:
    repo: SlootSantos/ec-store-module
